### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by OFlexan** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#15]
I've connected two PS motion controllers aswell as PSVR headset. They show up and light up when PSMoveServiceEx is started. However, SteamVR does not recognize it, and it shows this in Playstation VR Management:
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/c35c639c-685d-42c1-9573-5511d73c3cb5)

Upon fresh installing of the drivers it says I need to configure it, but no matter if I use direct or virtual mode it gives this error after configuring.

Might be unrelated, but I have the second HDMI cable of the VR box connected to the laptop (where PSMSE-VDM runs) and the other HDMI cable is not used. If I try the other HDMI on the VR box, it doesn't recognize it so I'm guessing it's not important (plugging it into a secondary laptop does nothing either and doesn't fix the issue), and I think it may be unrelevant but I wanted to say it anyways.

Display is in extend mode and when I move my mouse over there it does eat it up, so I don't know why it doesn't work. I'm pretty sure I'm also using AMD graphics but didn't confirm except for a property in system information.

**Comment by OFlexan** [comment]
May also be unrelevant but I'm trying to give as much information as possible, when changing the display frequency this pops up:
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/39fddcda-dab0-446a-a00f-632241b44c23)

**Comment by OFlexan** [comment]
Update, it now says this:
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/68cdc77c-7002-4244-bf53-0e15abdea7b2)
I enabled direct mode in SteamVR and it still says this. Anything else I need to do?

**Comment by Timocop** [comment]
Please attach both PSMoveServiceEx and Virtual Device Manager logs. You can find them in **VDM > System Management > Show service logs/Show application exceptions**

Also before you use Direct-Mode, make sure Virtual-Mode even works first. Direct-Mode only works on AMD/Intel GPUs because Nvidia needs some special care which i can not do right now. If nothing happens when enabling Direct-Mode in SteamVR then you have to fall back to Virtual-Mode. Make sure before enabling Virtual-Mode, disable SteamVR Direct-Mode first!

**Comment by OFlexan** [comment]
I swear I tried switching to virtual mode before, but apparently after switching it told me to replug indeed, and when I did that the refresh rate was too low, after that it fixed:
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/759e0b14-6232-4405-8308-f236582e27b1)

I don't think I have Nvidia, but atleast I'm glad it works this far. I now have different problems but I'll make a seperate issue for those.

Don't think it matters anymore but maybe for future reference, these are the logs:
`PSMoveServiceEx.log`:
```
[2024-07-02 14:32:27.595]: main - Starting PSMoveServiceEx v0.26.3.0 (protocol v0.9-alpha 9.0.0)
[2024-07-02 14:32:27.606]: C:\Users\Flexan\AppData\Roaming\PSMoveService\USBManagerConfig.json - Configuration loaded!
[2024-07-02 14:32:27.610]: C:\Users\Flexan\AppData\Roaming\PSMoveService\USBManagerConfig.json - {
    "version": "1",
    "usb_api": "libusb_api",
    "enable_usb_transfers": "true"
}

[2024-07-02 14:32:27.613]: C:\Users\Flexan\AppData\Roaming\PSMoveService\NetworkManagerConfig.json - Configuration loaded!
[2024-07-02 14:32:27.617]: C:\Users\Flexan\AppData\Roaming\PSMoveService\NetworkManagerConfig.json - {
    "version": "1",
    "server_port": "9512"
}

[2024-07-02 14:32:27.618]: USBAsyncRequestManager::startup - Requested LibUSBApi
[2024-07-02 14:32:27.621]: USBAsyncRequestManager::startup - Creating LibUSBApi
[2024-07-02 14:32:27.627]: USBAsyncRequestManager::startup - Initialized USB API
[2024-07-02 14:32:27.635]: C:\Users\Flexan\AppData\Roaming\PSMoveService\DeviceManagerConfig.json - Configuration loaded!
[2024-07-02 14:32:27.639]: C:\Users\Flexan\AppData\Roaming\PSMoveService\DeviceManagerConfig.json - {
    "version": "1",
    "legacy": "false",
    "controller_reconnect_interval": "1000",
    "tracker_reconnect_interval": "10000",
    "hmd_reconnect_interval": "10000",
    "gamepad_api_enabled": "true",
    "gamepad_api_xinput_only": "true",
    "platform_api_enabled": "true",
    "controller_poll_interval": "-0.100000001",
    "tracker_poll_interval": "-0.100000001",
    "hmd_poll_interval": "-0.100000001",
    "legacy_require_factory_reset": "false"
}

[2024-07-02 14:32:27.639]: DeviceManager::startup - Platform Hotplug API is ENABLED
[2024-07-02 14:32:27.649]: C:\Users\Flexan\AppData\Roaming\PSMoveService\ControllerManagerConfig.json - Configuration loaded!
[2024-07-02 14:32:27.653]: C:\Users\Flexan\AppData\Roaming\PSMoveService\ControllerManagerConfig.json - {
    "version": "1",
    "legacy": "false",
    "virtual_controller_count": "0"
}

[2024-07-02 14:32:27.801]: bluetooth_get_host_address - Failed to find a bluetooth radio
[2024-07-02 14:32:27.811]: C:\Users\Flexan\AppData\Roaming\PSMoveService\TrackerManagerConfig.json - Configuration loaded!
[2024-07-02 14:32:27.815]: C:\Users\Flexan\AppData\Roaming\PSMoveService\TrackerManagerConfig.json - {
    "version": "3",
    "legacy": "false",
    "virtual_tracker_count": "0",
    "ignore_pose_from_one_tracker": "true",
    "tracker_sync_mode": "0",
    "optical_tracking_timeout": "100",
    "use_bgr_to_hsv_lookup_table": "true",
    "thread_sleep_ms": "1",
    "excluded_opposed_cameras": "false",
    "min_valid_projection_area": "6",
    "occluded_area_on_loss_size": "4",
    "occluded_area_ignore_num_trackers": "0",
    "occluded_area_regain_projection_size": "32",
    "projection_collision_avoid": "true",
    "projection_collision_offset": "5",
    "average_position_cache_enabled": "true",
    "average_position_cache_cell_size": "5",
    "average_position_cache_avg_size": "30",
    "average_position_cache_limit": "1000",
    "min_points_in_contour": "4",
    "max_tracker_position_deviation": "15",
    "disable_roi": "false",
    "autoscale_roi": "true",
    "optimized_roi": "true",
    "roi_size": "32",
    "roi_search_size": "164",
    "roi_edge_offset": "4",
    "position_interpolation": "true",
    "angular_interpolation": "true",
    "thread_maximum_framrate": "200",
    "default_tracker_profile": {
        "frame_width": "640",
        "frame_rate": "30",
        "exposure": "32",
        "gain": "32",
        "color_preset": {
            "magenta": {
                "hue_center": "150",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "cyan": {
                "hue_center": "90",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "yellow": {
                "hue_center": "30",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "red": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "green": {
                "hue_center": "60",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "blue": {
                "hue_center": "120",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom0": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom1": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom2": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom3": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom4": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom5": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom6": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom7": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom8": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "custom9": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            }
        }
    },
    "global_forward_degrees": "270",
    "playspace_orientation_yaw": "0",
    "playspace_position_x": "0",
    "playspace_position_y": "0",
    "playspace_position_z": "0",
    "playspace_scale_x": "1",
    "playspace_scale_y": "1",
    "playspace_scale_z": "1"
}

[2024-07-02 14:32:27.819]: C:\Users\Flexan\AppData\Roaming\PSMoveService\HMDManagerConfig.json - Configuration loaded!
[2024-07-02 14:32:27.822]: C:\Users\Flexan\AppData\Roaming\PSMoveService\HMDManagerConfig.json - {
    "version": "1",
    "legacy": "false",
    "virtual_hmd_count": "0",
    "enable_morpheus": "true"
}

[2024-07-02 14:32:27.823]: PSMoveServiceEx - ------------------------------------------
[2024-07-02 14:32:27.826]: PSMoveServiceEx - Startup successful! Entering main loop...
[2024-07-02 14:32:27.829]: PSMoveServiceEx - ------------------------------------------
[2024-07-02 14:32:27.832]: PSMoveServiceEx - GitHub: https://github.com/Timocop/PSMoveServiceEx
[2024-07-02 14:32:27.836]: PSMoveServiceEx - ------------------------------------------
[2024-07-02 14:32:27.936]: MorpheusHMD::open - Opening MorpheusHMD(USB\VID_054c&PID_09af).
[2024-07-02 14:32:27.973]: morpeus_open_usb_device - libusb_open index 3 returned LIBUSB_ERROR_NOT_SUPPORTED
[2024-07-02 14:32:27.979]: morpeus_open_usb_device - libusb_open index 6 returned LIBUSB_SUCCESS / LIBUSB_TRANSFER_COMPLETED
[2024-07-02 14:32:27.987]: C:\Users\Flexan\AppData\Roaming\PSMoveService\MorpheusHMDConfig.json - Configuration loaded!
[2024-07-02 14:32:27.987]: WorkerThread::start - Starting worker thread: MorpheusSensorProcessor
[2024-07-02 14:32:27.995]: C:\Users\Flexan\AppData\Roaming\PSMoveService\MorpheusHMDConfig.json - {
    "is_valid": "false",
    "version": "2",
    "legacy": "false",
    "Calibration": {
        "Accel": {
            "X": {
                "k": "0.0009765625",
                "b": "0"
            },
            "Y": {
                "k": "0.0009765625",
                "b": "0"
            },
            "Z": {
                "k": "0.0009765625",
                "b": "0"
            },
            "Variance": "0"
        },
        "Gyro": {
            "X": {
                "k": "0.00106526446",
                "b": "0"
            },
            "Y": {
                "k": "0.00106526446",
                "b": "0"
            },
            "Z": {
                "k": "0.00106526446",
                "b": "0"
            },
            "Variance": "1.33875039e-06",
            "Drift": "0.00110168592"
        },
        "Identity": {
            "Gravity": {
                "X": "0",
                "Y": "1",
                "Z": "-0"
            }
        },
        "Position": {
            "VarianceExpFitA": "0.0994158462",
            "VarianceExpFitB": "-0.000567041978"
        },
        "Orientation": {
            "Variance": "0.00499999989"
        },
        "Time": {
            "MeanUpdateTime": "0.00833300035"
        }
    },
    "OrientationFilter": {
        "FilterType": "MadgwickARG"
    },
    "PositionFilter": {
        "FilterType": "PositionKalman",
        "MaxVelocity": "1"
    },
    "Offsets": {
        "Position": {
            "X": "0",
            "Y": "0",
            "Z": "0"
        },
        "LocalOrientation": {
            "X": "0",
            "Y": "0",
            "Z": "0"
        },
        "WorldOrientation": {
            "X": "0",
            "Y": "0",
            "Z": "0"
        },
        "Scale": {
            "X": "1",
            "Y": "1",
            "Z": "1"
        }
    },
    "prediction_time": "0",
    "ang_prediction_time": "0",
    "max_poll_failure_timeout_ms": "3000",
    "FilterSettings": {
        "LowPassOptical": {
            "Distance": "1",
            "Smoothing": "0.100000001"
        },
        "Madgwick": {
            "Beta": "0.0500000007",
            "Stabilization": "true",
            "StabilizationMinBeta": "0",
            "StabilizationSmoothingFactor": "0.100000001",
            "SmartEnabled": "true"
        },
        "VelocitySmoothingFactor": "0.25",
        "AngularSmoothingFactor": "0.25",
        "VelocityPredictionCutoff": "1",
        "AngularPredictionCutoff": "0",
        "PositionKalman": {
            "Error": "10",
            "ProcessNoise": "200",
            "DisableCutoff": "true"
        }
    },
    "use_custom_optical_tracking": "true",
    "override_custom_tracking_leds": "0",
    "tracking_color": "blue"
}

[2024-07-02 14:32:27.995]: MorpheusHMD::open - Turning on MorpheusHMD power.
[2024-07-02 14:32:27.999]: MorpheusHMD::open - Turning on MorpheusHMD VR-Mode.
[2024-07-02 14:32:31.19]: DeviceTypeManager::update_connected_devices - Device device_id 0 (Morpheus) opened
[2024-07-02 14:32:31.26]: updatePoseFilter() - Incoming packet count: 6170 (9.21939e+06ms), trimming: 5170
[2024-07-02 14:32:31.32]: PSMoveServiceEx - ------------------------------------------
[2024-07-02 14:32:31.35]: PSMoveServiceEx - Successfully Initialized!
[2024-07-02 14:32:31.38]: PSMoveServiceEx - ------------------------------------------
[2024-07-02 14:32:31.41]: PSMoveServiceEx - Maximum thread framerate is: 200
[2024-07-02 14:32:31.44]: PSMoveServiceEx - Calculating average main thread FPS...
[2024-07-02 14:32:32.238]: ClientConnection::start - Starting client connection id 0
[2024-07-02 14:32:32.242]: ClientConnection::send_connection_info - Sending connection id to client 0
[2024-07-02 14:32:32.344]: ServerRequestHandler - Start hmd(0) stream (pos=0,phys=0,raw_sens=0,cal_sens=0,trkr=0,roi=0)
[2024-07-02 14:32:41.50]: PSMoveServiceEx - Main thread running at 193 FPS average. Lowest FPS was 189.
[2024-07-02 14:32:42.839]: ServerRequestHandler - Start hmd(0) stream (pos=1,phys=0,raw_sens=0,cal_sens=0,trkr=0,roi=0)
```

`application_error.ini`:
```
[2141043967]
Message=Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
StackTrace=   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)\n   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)\n   at PSMSVirtualDeviceManager.UCVmtManagement.OscStatusThread()
Date=07/02/2024 14:23:35
Count=1
Version=13.3.9.0
[-1476424085]
Message=Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
StackTrace=   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)\n   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)\n   at PSMSVirtualDeviceManager.UCVmtManagement.OscDeviceStatusThread()
Date=07/02/2024 14:23:35
Count=1
Version=13.3.9.0
[1404957938]
Message=Exception of type 'PSMoveServiceExCAPI.ServiceExceptions+ServiceRequestFailed' was thrown.
StackTrace=   at PSMoveServiceExCAPI.ServiceExceptions.ThrowExceptionServiceRequest(String sMessage, PSMResult iResult)\n   at PSMoveServiceExCAPI.PSMoveServiceExCAPI.Service.Connect(Int32 iTimeout)\n   at PSMSVirtualDeviceManager.ClassServiceClient.ProcessingThread()
Date=07/02/2024 14:32:27
Count=69
Version=13.3.9.0
[-1379666653]
Message=Changing display frequency failed with error: -1 - DISP_CHANGE_FAILED
StackTrace=   at PSMSVirtualDeviceManager.FormDisplayFrequency.Button_Apply_Click(Object sender, EventArgs e)
Date=07/02/2024 14:07:46
Count=1
Version=13.3.9.0
[1412313768]
Message=OSC server is not running
StackTrace=   at PSMSVirtualDeviceManager.UCVirtualMotionTrackerItem.ClassIO.ThreadOsc()
Date=07/02/2024 14:15:29
Count=424
Version=13.3.9.0
[2129763082]
Message=Could not find any recognizable digits.
StackTrace=   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)\n   at System.Convert.ToInt32(String value, Int32 fromBase)\n   at PSMSVirtualDeviceManager.UCVirtualMotionTrackerItem.ClassIO.ThreadOsc()
Date=07/02/2024 14:23:23
Count=90
Version=13.3.9.0
[-37516125]
Message=PSMoveServiceEx is running. Please close PSMoveServiceEx!
StackTrace=   at PSMSVirtualDeviceManager.UCStartPage._Lambda$__435-0()
Date=07/02/2024 14:23:21
Count=1
Version=13.3.9.0
[1298988685]
Message=OSC server is suspended
StackTrace=   at PSMSVirtualDeviceManager.UCVirtualMotionTrackerItem.ClassIO.ThreadOsc()
Date=07/02/2024 14:32:42
Count=45
Version=13.3.9.0
```
